export const LOAN_APPLICATION_FORM = {
    LOAN_APPLICATION_FORM_TITLE: 'Loan Application Form',
    TERMS_IN_YEARS: 'Terms(In yrs)',
    LOAN_USAGE: 'Loan will be used for',
    SECURITIES: 'Securities',
    COLLATERAL_TYPE: 'Collateral Type',
    BANK_NAME: 'Bank Name',
    ACCOUNT_NUMBER: 'Account Number',
    BALANCE: 'Balance',
    CONTACT_INFORMATION: 'Contact Informaction',
    FIRST_NAME: 'First Name',
    LAST_NAME: 'Last Name',
    DOB: 'DOB',
    MARITAL_STTAUS: 'Marital Status',
    EMAIL: 'E-mail',
    PHONE: 'Phone',
    ADDRESS: 'Address',
    STREET_ADDRESS: 'Street Address',
    CITY: 'City',
    STATE: 'State / Province',
    ZIP_CODE: 'Postal / Zip Code',
    COUNTRY: 'Country',
    LOAN_AMOUNT: 'Loan Amount',
    EMPLOYMENT_INFORMATION: 'Employment Information',
    PRESENT_EMPLOYER: 'resent Employer',
    OCCUPATION: 'Occupation',
    INCOME: 'Gross monthly income',
    EXPERIENCE: 'Years of experience',
    BANK_REFERENCE: 'Bank References',
    INSTITUTION_NAME: 'Institution Name',
    ACCOUNT_TYPE: 'Account Type',
    CONCENT_MESSAGE: 'I hereby agree that the information given is true, accurate and complete as of the date of this application submission.',
    SEND_BTN: 'Send Application Now',
    CONCENT: 'Consent'
}
export const COMMON = {
    YES: 'Yes'
}
